name: Deploy to Local Server

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  build_deploy:
    runs-on: self-hosted

    steps:
      # Шаг 1: Скачиваем свежий код прямо на домашний сервер
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Сборка Docker-образа локально
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag discordnexusbot:latest

      # Шаг 3: Остановка старого контейнера и создание томов
      - name: Stop and remove old container, create volumes
        run: |
          docker stop nexusbot || true
          docker rm nexusbot || true
          docker volume create chroma_data || true

      # Шаг 4: Запуск нового контейнера с передачей всех нужных переменных окружения и томов
      - name: Run new container
        run: |
          docker run -d --name nexusbot \
            --restart unless-stopped \
            -v chroma_data:/python-app/chroma_db \
            -e DC_TOKEN="${{ secrets.DC_TOKEN }}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e AI_TOKEN_POLZA="${{ secrets.AI_TOKEN_POLZA }}" \
            -e SCREENSHOT_CHANNEL_ID="${{ secrets.SCREENSHOT_CHANNEL_ID }}" \
            discordnexusbot:latest

      # Шаг 5: Очистка старых "повисших" образов, чтобы не забивать память
      - name: Clean up unused Docker images
        run: docker image prune -f
